name: "Update README"
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright
      - name: Install browsers
        run: playwright install
      - name: Update README
        run: python update_readme.py
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add screenshot.jpg
          git commit -m "Update screenshot"
          git push origin main
